/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module output_handler_22 (
    input rst,
    input clk,
    input [255:0] grid,
    input [1:0] current_player,
    output reg outled,
    output reg [1:0] current_player_LED_sig,
    input valid_led_on,
    input buzzer_on,
    output reg buzzer_output
  );
  
  
  
  wire [6-1:0] M_led_strip_pixel;
  wire [1-1:0] M_led_strip_led;
  reg [1-1:0] M_led_strip_update;
  reg [24-1:0] M_led_strip_color;
  ws2812b_writer_29 led_strip (
    .clk(clk),
    .rst(rst),
    .update(M_led_strip_update),
    .color(M_led_strip_color),
    .pixel(M_led_strip_pixel),
    .led(M_led_strip_led)
  );
  
  wire [1-1:0] M_buzzer_system_out;
  reg [1-1:0] M_buzzer_system_trigger_sig;
  buzzer_30 buzzer_system (
    .clk(clk),
    .rst(rst),
    .trigger_sig(M_buzzer_system_trigger_sig),
    .out(M_buzzer_system_out)
  );
  
  
  localparam PLAYER1_current_player_storage = 1'd0;
  localparam PLAYER2_current_player_storage = 1'd1;
  
  reg M_current_player_storage_d, M_current_player_storage_q = PLAYER1_current_player_storage;
  
  always @* begin
    M_current_player_storage_d = M_current_player_storage_q;
    
    M_led_strip_update = 1'h1;
    M_led_strip_color = 24'h000000;
    if (grid[0+(M_led_strip_pixel)*1+0-:1] == 1'h1) begin
      M_led_strip_color = 24'h000010;
    end
    if (grid[64+(M_led_strip_pixel)*1+0-:1] == 1'h1) begin
      M_led_strip_color = 24'h300000;
    end
    if (grid[128+(M_led_strip_pixel)*1+0-:1] == 1'h1) begin
      if (valid_led_on) begin
        M_led_strip_color = 24'h101000;
      end
      if (grid[192+(M_led_strip_pixel)*1+0-:1] == 1'h1) begin
        M_led_strip_color = 24'h100100;
      end
    end
    current_player_LED_sig = 1'h0;
    buzzer_output = M_buzzer_system_out;
    M_buzzer_system_trigger_sig = 1'h0;
    if (current_player == 2'h1) begin
      M_current_player_storage_d = PLAYER1_current_player_storage;
      current_player_LED_sig = 2'h1;
      if (M_current_player_storage_q == PLAYER2_current_player_storage) begin
        M_current_player_storage_d = PLAYER1_current_player_storage;
        if (buzzer_on) begin
          M_buzzer_system_trigger_sig = 1'h1;
        end
      end
    end else begin
      if (current_player == 2'h2) begin
        M_current_player_storage_d = PLAYER2_current_player_storage;
        current_player_LED_sig = 2'h2;
        if (M_current_player_storage_q == PLAYER1_current_player_storage) begin
          M_current_player_storage_d = PLAYER2_current_player_storage;
          if (buzzer_on) begin
            M_buzzer_system_trigger_sig = 1'h1;
          end
        end
      end
    end
    outled = M_led_strip_led;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_current_player_storage_q <= 1'h0;
    end else begin
      M_current_player_storage_q <= M_current_player_storage_d;
    end
  end
  
endmodule
