/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module player_button_handler_21 (
    input [4:0] player_button,
    output reg [2:0] out
  );
  
  
  
  always @* begin
    
    case (player_button)
      5'h01: begin
        out = 3'h1;
      end
      5'h02: begin
        out = 3'h2;
      end
      5'h04: begin
        out = 3'h3;
      end
      5'h08: begin
        out = 3'h4;
      end
      5'h10: begin
        out = 3'h5;
      end
      default: begin
        out = 3'h0;
      end
    endcase
  end
endmodule
