/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     WORDS = MEMORY_SIZE
*/
module memory_unit_10 (
    input clk,
    input [11:0] ia,
    input instruction_write_enable,
    input [31:0] instruction_towrite,
    output reg [31:0] id
  );
  
  localparam WORDS = 10'h2a8;
  
  
  wire [32-1:0] M_instruction_memory_read_data;
  reg [10-1:0] M_instruction_memory_address;
  reg [32-1:0] M_instruction_memory_write_data;
  reg [1-1:0] M_instruction_memory_write_en;
  simple_ram_23 #(.SIZE(6'h20), .DEPTH(10'h2a8)) instruction_memory (
    .clk(clk),
    .address(M_instruction_memory_address),
    .write_data(M_instruction_memory_write_data),
    .write_en(M_instruction_memory_write_en),
    .read_data(M_instruction_memory_read_data)
  );
  
  always @* begin
    M_instruction_memory_write_data = instruction_towrite;
    M_instruction_memory_address = ia[2+9-:10];
    M_instruction_memory_write_en = instruction_write_enable;
    id = M_instruction_memory_read_data;
  end
endmodule
